# Use root/example as user/password credentials
version: '3.1'

services:
        xrdp:
                build: .
                hostname: 'xrdp'
                ports:
                        - "3389:3389"
                cap_add:
                        - NET_ADMIN
                        - SETUID
